#!/usr/bin/env python3
"""Generate a Krait CPU OPP table from Sony's stock device tree.

Sony's DTB carries the factory frequency/voltage tables for every speed bin
and PVS (process) bin, as qcom,speed<S>-pvs<P>-bin-v<V> properties on the
qcom,clock-krait-8974 node. Each is a flat list of triplets:

    <frequency-Hz  voltage-uV  current-mA>

qcom-cpufreq-nvmem reads the qfprom speed/PVS bin at boot, then asks the OPP
core for properties named "opp-microvolt-speed<S>-pvs<P>-v<V>" and matches
opp-supported-hw against (1 << speed).  This script emits exactly that shape.

Usage:  gen-krait-opp.py <fota-dtb0.dts> [--cap-hz N] [--out FILE]

--cap-hz marks every OPP above N as status="disabled".  That is the safety
control: with no driver for the Krait per-core LDO/BHS regulator, Linux
cannot raise CPU voltage, so only frequencies the current rail already
supports may be enabled.  See README.md.
"""
import argparse, re, sys
from collections import defaultdict

# Upper end of each OPP's voltage window: the SAW2 regulator's max.  Four
# CPUs share one supply with independent policies, so each asks for
# <target min max>; exact single values from different cores would conflict.
VMAX = 1120000

PROP = re.compile(r'qcom,speed(\d+)-pvs(\d+)-bin-v(\d+)\s*=\s*<([^>]*)>')


def parse(path):
    text = open(path, encoding='utf-8', errors='replace').read()
    # freq -> {(speed,pvs,ver): microvolt}
    table = defaultdict(dict)
    speeds = defaultdict(set)          # speed -> set of freqs
    bins = set()
    for m in PROP.finditer(text):
        speed, pvs, ver = int(m.group(1)), int(m.group(2)), int(m.group(3))
        vals = [int(v, 16) for v in m.group(4).split()]
        if len(vals) % 3:
            sys.exit(f'speed{speed}-pvs{pvs}-v{ver}: {len(vals)} values, not a multiple of 3')
        bins.add((speed, pvs, ver))
        for i in range(0, len(vals), 3):
            hz, uv, _ma = vals[i:i + 3]
            if hz == 0:
                continue           # leading zero row
            table[hz][(speed, pvs, ver)] = uv
            speeds[speed].add(hz)
    return table, speeds, bins


def emit(table, speeds, cap_hz):
    out = []
    out.append('// SPDX-License-Identifier: GPL-2.0')
    out.append('/*')
    out.append(' * Krait CPU operating points for MSM8974.')
    out.append(' *')
    out.append(' * GENERATED by cpufreq/gen-krait-opp.py from Sony\'s stock device tree.')
    out.append(' * Do not edit by hand; regenerate with a different --cap-hz instead.')
    out.append(' *')
    out.append(' * Every OPP above the cap carries status = "disabled" because Linux has')
    out.append(' * no driver for the Krait per-core LDO/BHS regulator and so cannot raise')
    out.append(' * CPU voltage. See cpufreq/README.md.')
    out.append(' */')
    out.append('')
    out.append('/ {')
    out.append('\tcpu_opp_table: opp-table-cpu {')
    out.append('\t\tcompatible = "operating-points-v2-krait-cpu";')
    out.append('\t\tnvmem-cells = <&speedbin_efuse>;')
    out.append('')
    for hz in sorted(table):
        mask = 0
        for (speed, _pvs, _ver) in table[hz]:
            mask |= 1 << speed
        out.append(f'\t\topp-{hz} {{')
        out.append(f'\t\t\topp-hz = /bits/ 64 <{hz}>;')
        out.append(f'\t\t\topp-supported-hw = <0x{mask:x}>;')
        for (speed, pvs, ver), uv in sorted(table[hz].items()):
            out.append(f'\t\t\topp-microvolt-speed{speed}-pvs{pvs}-v{ver} = <{uv} {uv} {VMAX}>;')
        if hz > cap_hz:
            out.append('\t\t\tstatus = "disabled";\t/* above the safe rail cap */')
        out.append('\t\t};')
        out.append('')
    out.append('\t};')
    out.append('};')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('dts')
    ap.add_argument('--cap-hz', type=int, default=576000000)
    ap.add_argument('--out')
    a = ap.parse_args()

    table, speeds, bins = parse(a.dts)
    if not table:
        sys.exit('no qcom,speed*-pvs*-bin-v* properties found')

    enabled = [h for h in table if h <= a.cap_hz]
    sys.stderr.write(
        f'{len(bins)} factory bins, {len(table)} distinct frequencies\n'
        f'range {min(table)/1e6:.1f}-{max(table)/1e6:.1f} MHz\n')
    for s in sorted(speeds):
        sys.stderr.write(f'  speed{s}: {len(speeds[s])} steps, max {max(speeds[s])/1e6:.1f} MHz\n')
    sys.stderr.write(f'cap {a.cap_hz/1e6:.1f} MHz -> {len(enabled)} enabled, '
                     f'{len(table)-len(enabled)} disabled\n')

    text = emit(table, speeds, a.cap_hz)
    if a.out:
        open(a.out, 'w').write(text + '\n')
        sys.stderr.write(f'wrote {a.out}\n')
    else:
        print(text)


if __name__ == '__main__':
    main()
