# Out-of-tree build of the PM8941 clock-divider driver.
#
#   make -C <kernel build dir> M=$PWD modules
#
# On the phone:
#   make -s LLVM=1 -C ~/kbuild/linux-6.16.12 M=$PWD

obj-m += clk-spmi-pmic-div.o
